Add Jazzy job configurations.
ros2/ros_buildfarm_config pull request #301
Opened 2024-04-22 23:29 UTC by nuclearsandwich

Adds CI, documentation, release source, and binary jobs for ROS 2 Jazzy. Based on the ROS 2 Rolling configurations with: `sed -i 's/rolling/jazzy/g'`.

2024-04-22 23:34 UTC, clalancette requested changes

2024-04-22 23:34 UTC, clalancette commented on index.yaml
> +      nightly-cross-vendor-cyclonedds-fastrtps: rollingjazzyci-nightly-cross-vendor-cyclonedds-fastrtps.yaml
```suggestion
      nightly-cross-vendor-cyclonedds-fastrtps: jazzy/ci-nightly-cross-vendor-cyclonedds-fastrtps.yaml
```

2024-04-22 23:36 UTC, nuclearsandwich commented on index.yaml
> +      nightly-cross-vendor-cyclonedds-fastrtps: rollingjazzyci-nightly-cross-vendor-cyclonedds-fastrtps.yaml
b9692e9c6fb8020ee2556cf490f6b009ff335f26

2024-04-22 23:36 UTC, clalancette approved these changes
Looks good to me, thanks for doing this!

2024-04-23 06:52 UTC, marcoag approved these changes

2024-04-23 07:06 UTC, merged

2024-04-23 18:34 UTC, nuclearsandwich commented
Commands for deploying jazzy to the buildfarm:

```
# Dry-run to make sure things is good
❯ generate_all_jobs.py https://raw.githubusercontent.com/ros2/ros_buildfarm_config/ros2/index.yaml --ros-distro-names jazzy
# Review the output ...
❯ generate_all_jobs.py https://raw.githubusercontent.com/ros2/ros_buildfarm_config/ros2/index.yaml --ros-distro-names jazzy --commit
...
❯ generate_release_trigger_upload_jobs.py https://raw.githubusercontent.com/ros2/ros_buildfarm_config/ros2/index.yaml
```

2024-04-30 06:59 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/jazzy-pre-release-is-ready-for-the-tutorial-party/37472/1